version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      target: serve

    image: dinuka029/co227

    ports:
      - 80:80
    restart: always
    

  server:
    container_name: server
    build:
      context: ./server
      target: build
    
    image: dinuka029/co227
    
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=lckandy.clmtqbwd31v1.ap-south-1.rds.amazonaws.com
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=lckandyadmin
      - DATABASE_DB=LC_KANDY
      - DATABASE_PORT=3306
    restart: always
